@baseUrl = http://localhost:3000

### Hello
GET {{baseUrl}}/

### Not Found
GET {{baseUrl}}/fail

### View without query param
GET {{baseUrl}}/snippet/view

### View with query param
GET {{baseUrl}}/snippet/view?id=29

### Create with GET
GET {{baseUrl}}/snippet/create

### Create with POST
POST {{baseUrl}}/snippet/create